import Head from 'next/head'
import Image from 'next/image'

import Post from '../src/Components/Post'
import styles from '../styles/Home.module.scss'
import PostForm from '../src/Components/PostForm'
import Bio from '../src/Components/Bio/Bio'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Bio
          headshot="https://scontent.fdad3-1.fna.fbcdn.net/v/t39.30808-6/274450527_686455959061577_8143687573055724049_n.jpg?_nc_cat=110&ccb=1-6&_nc_sid=09cbfe&_nc_ohc=iaAsDnX0djAAX8eMPcJ&_nc_ht=scontent.fdad3-1.fna&oh=00_AT_Oz1n96DH05B89CnmjnQSzs6fTpZ0Z0OxW_svFjfu65w&oe=627AD00D"
          name="Colby Fayock"
          tagline="Helping others to leanrn by doing"
          role="Developer Advocate @ Applitools"
        />
        <ul className={styles.posts}>
          <li>
            <Post
              content={"Hello xin chào mọi người mình tên là đậu văn nam"}
              date={"3/3/2021"} />
          </li>
          <li>
            <Post
              content={"Hello xin chào mọi người mình tên là đậu văn nam"}
              date={"3/3/2021"} />
          </li>
          <li>
            <Post
              content={"Hello xin chào mọi người mình tên là đậu văn nam"}
              date={"3/3/2021"} />
          </li>
          <li>
            <Post
              content={"Hello xin chào mọi người mình tên là đậu văn nam"}
              date={"3/3/2021"} />
          </li>
          <li>
            <Post
              content={"Hello xin chào mọi người mình tên là đậu văn nam"}
              date={"3/3/2021"} />
          </li>
          <li>
            <Post
              content={"Hello xin chào mọi người mình tên là đậu văn nam"}
              date={"3/3/2021"} />
          </li>
        </ul>
        <PostForm />
      </main>

    </div>
  )
}
